# Nombre del pipeline
name: 'CI-Pipeline-SpringBoot'

# Configuración del pool de agentes (self-hosted)
pool:
  name: 'Self-hosted'  # Sin especificar demandas

# Disparador para ejecutar el pipeline cuando se hagan cambios en la rama master
trigger:
  branches:
    include:
      - master

# Definición de las etapas y pasos
steps:
  - script: |
      java -version
      mvn -v
    displayName: 'Verificar Java y Maven'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
    displayName: 'Instalar dependencias y compilar con Maven'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
    displayName: 'Ejecutar pruebas unitarias con Maven'
