# Nombre del pipeline
name: 'CI-Pipeline-SpringBoot'

# Configuración del pool de agentes (self-hosted)
pool:
  name: 'Self-hosted'  # Asegúrate de que el nombre del pool sea correcto

# Disparador para ejecutar el pipeline cuando se hagan cambios en la rama master
trigger:
  branches:
    include:
      - master  # Cambia a "main" si tu rama principal se llama "main"

# Definición de las etapas y pasos
steps:
  # Paso 1: Comprobar la versión de Java y Maven
  - script: |
      java -version
      mvn -v
    displayName: 'Verificar Java y Maven'

  # Paso 2: Instalar dependencias con Maven y compilar
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'  # Asegúrate de que esta ruta apunte al archivo POM en tu proyecto
      goals: 'clean install'
    displayName: 'Instalar dependencias y compilar con Maven'

  # Paso 3: Ejecutar pruebas unitarias
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
    displayName: 'Ejecutar pruebas unitarias con Maven'

  # Paso 4: Empaquetar el proyecto (opcional)
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
    displayName: 'Empaquetar el proyecto con Maven'

  # Paso 5: Publicar los resultados de las pruebas
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    displayName: 'Publicar resultados de las pruebas'

  # Paso 6: Publicar el artefacto generado (.jar)
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/target/*.jar'  # Ruta hacia el archivo .jar generado
      artifact: 'drop'
    displayName: 'Publicar artefacto .jar'
