  version: '3.8'
  services:
    mysql:
      image: mysql:8.0
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: Admin32.
        MYSQL_DATABASE: dbmovies
      ports:
        - "3306:3306"
      volumes:
          - mysql-data:/var/lib/mysql
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        interval: 5s
        timeout: 5s
        retries: 5

    app:
      image: jackblaze/movie-app
      container_name: springboot-movie-app
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbmovies
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: Admin32.
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
      depends_on:
        mysql:
          condition: service_healthy
  volumes:
    mysql-data:
